const crypto = require("crypto");
const https = require("https");
const {
  PHONEPE_MERCHANT_ID,
  PHONEPE_SALT_KEY,
  PHONEPE_SALT_INDEX,
  PHONEPE_BASE_URL,
} = require("../config/phonepe");

/**
 * Creates a PhonePe payment request and returns the redirect URL.
 * @param {number} amountInRupees
 * @param {string} merchantTransactionId - unique transaction ID (generated by us)
 * @param {string} userId - authenticated user ID
 * @param {string} callbackUrl - backend URL PhonePe POSTs to after payment
 * @param {string} redirectUrl - frontend URL to redirect user after payment
 */
const createPhonePePaymentRequest = async (
  amountInRupees,
  merchantTransactionId,
  userId,
  callbackUrl,
  redirectUrl
) => {
  const amountInPaise = Math.round(amountInRupees * 100);

  const payload = {
    merchantId: PHONEPE_MERCHANT_ID,
    merchantTransactionId: merchantTransactionId,
    merchantUserId: `UEM_${userId.replace(/-/g, "").slice(0, 20)}`,
    amount: amountInPaise,
    redirectUrl: redirectUrl,
    redirectMode: "REDIRECT",
    callbackUrl: callbackUrl,
    paymentInstrument: {
      type: "PAY_PAGE",
    },
  };

  const payloadBase64 = Buffer.from(JSON.stringify(payload)).toString("base64");

  // Compute SHA256 checksum: base64(payload) + "/pg/v1/pay" + saltKey
  const checksumString = `${payloadBase64}/pg/v1/pay${PHONEPE_SALT_KEY}`;
  const sha256 = crypto.createHash("sha256").update(checksumString).digest("hex");
  const checksum = `${sha256}###${PHONEPE_SALT_INDEX}`;

  const requestBody = JSON.stringify({ request: payloadBase64 });

  return new Promise((resolve, reject) => {
    const url = new URL(`${PHONEPE_BASE_URL}/pg/v1/pay`);
    const options = {
      hostname: url.hostname,
      path: url.pathname,
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "Content-Length": Buffer.byteLength(requestBody),
        "X-VERIFY": checksum,
        accept: "application/json",
      },
    };

    const req = https.request(options, (res) => {
      let data = "";
      res.on("data", (chunk) => (data += chunk));
      res.on("end", () => {
        try {
          const parsed = JSON.parse(data);
          if (
            parsed.success &&
            parsed.data &&
            parsed.data.instrumentResponse &&
            parsed.data.instrumentResponse.redirectInfo
          ) {
            resolve({
              redirectUrl: parsed.data.instrumentResponse.redirectInfo.url,
              merchantTransactionId,
            });
          } else {
            reject(new Error(parsed.message || "PhonePe payment initiation failed"));
          }
        } catch (e) {
          reject(new Error("Invalid response from PhonePe API"));
        }
      });
    });

    req.on("error", (e) => reject(new Error(`PhonePe API request error: ${e.message}`)));
    req.write(requestBody);
    req.end();
  });
};

/**
 * Verifies PhonePe callback/status response signature.
 * @param {string} base64Response - the encoded response body from PhonePe callback
 * @param {string} receivedChecksum - X-VERIFY header value from PhonePe
 */
const verifyPhonePeCallback = (base64Response, receivedChecksum) => {
  const checksumString = `${base64Response}/pg/v1/status${PHONEPE_SALT_KEY}`;
  const expectedHash = crypto.createHash("sha256").update(checksumString).digest("hex");
  const expectedChecksum = `${expectedHash}###${PHONEPE_SALT_INDEX}`;
  return expectedChecksum === receivedChecksum;
};

/**
 * Checks payment status directly with PhonePe (for server-side verification).
 * @param {string} merchantTransactionId
 */
const checkPhonePePaymentStatus = async (merchantTransactionId) => {
  const statusPath = `/pg/v1/status/${PHONEPE_MERCHANT_ID}/${merchantTransactionId}`;
  const checksumString = `${statusPath}${PHONEPE_SALT_KEY}`;
  const sha256 = crypto.createHash("sha256").update(checksumString).digest("hex");
  const checksum = `${sha256}###${PHONEPE_SALT_INDEX}`;

  return new Promise((resolve, reject) => {
    const url = new URL(`${PHONEPE_BASE_URL}${statusPath}`);
    const options = {
      hostname: url.hostname,
      path: url.pathname,
      method: "GET",
      headers: {
        "Content-Type": "application/json",
        "X-VERIFY": checksum,
        "X-MERCHANT-ID": PHONEPE_MERCHANT_ID,
        accept: "application/json",
      },
    };

    const req = https.request(options, (res) => {
      let data = "";
      res.on("data", (chunk) => (data += chunk));
      res.on("end", () => {
        try {
          resolve(JSON.parse(data));
        } catch (e) {
          reject(new Error("Invalid status response from PhonePe API"));
        }
      });
    });

    req.on("error", (e) => reject(new Error(`PhonePe status check error: ${e.message}`)));
    req.end();
  });
};

module.exports = {
  createPhonePePaymentRequest,
  verifyPhonePeCallback,
  checkPhonePePaymentStatus,
};
